version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  web-app:
    build: ./semantic_search/
    restart: always
    container_name: web-app
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - elastic
    

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge 